### ISSUE TITLE
Process time via CURL request

### ISSUE THREAD

**Issue by simonfreeman80** [vulcan25/image_processor#4]
Hi @vulcan25 , just noticed after doing some testing, processing time via CURL request request 2/3x time more that using the frontend. Just wondering to understand how optimize this as API feature. Is it possibile to have a processing queue like in the testing frontend? Thanks

**Comment by vulcan25** [comment]
I've added some improvements to the timing functionality at https://github.com/vulcan25/image_processor/commit/b8a9a16c3c5814a163f9367e5718a2cbdfa9fa7d

This means rather than just printing to the terminal, the timings are returned along with the `info` dict.  Something like:

    "timings":"detect_img: 0.901s, meta: 0.001s, "

As you can see the result for `detect_img` times the following lines:
```
     is_success, output_stream, ObjectsList  = yolo.detect_img(input_stream)
     io_buf = io.BytesIO(output_stream)
```
`meta` includes building the `object_string` and the redis increments, which is negligible.

These are visible in the curl response, and I've also added some code to display this on the frontend.

---

> just noticed after doing some testing, processing time via CURL request request 2/3x time more that using the frontend. Just wondering to understand how optimize this as API feature.

I can't seem to recreate this.  What I am finding is when I launch with `docker-compose up --build` the first time I submit the [hydrant] image the processing time is `3.523s`.*  If I run the same curl command again it drops to: `0.909s`.  Subsequent runs are:  `0.887s,  0.889s,  0.877s, 0.877s`

If I restart the docker service, then try submitting through the front-end ( **Directly process an image...** ) the results are much the same: `~3.4s` for the first, then `~0.89s` for subsequent submissions of the same image.

If I immediately submit to the front-end, having already submitted by curl, but without restarting the docker service between, then the frontend result for that image is again `~0.89s`.  So I'm not seeing much difference between the frontend and curl method of submitting.

*I'm aware in this configuration that the models are loaded when the server starts, so I'm not sure why the first image submission takes longer.  Probably something to do with the keras session (?)

---

> Is it possibile to have a processing queue like in the testing frontend? 

What do you mean by 'testing frontend'?  I think you may be referring to what the README calls 'mode(2)' - deployment with an rq queue.

With this mode it would be possible to handle many curl requests quickly - items are placed in the queue and a response is sent immediately to each curl request issued.  This is good for fast ingres of images.  **However the current bug with this method of deployment is that every time an individual job runs, all the dependencies are loaded, which was resulting in `~13s` processing time per image; not ideal.**  I haven't had a chance to look at this yet, as most of what I added in the last few commits relates to `mode(1)`.

---

Hopefully I haven't misunderstood what you're asking...

**Comment by simonfreeman80** [comment]
Hi, yes you fully understood my question despite I was not super clear! :)
I checked again and the timing CURL Vs FrontEnd: they are absolutely comparable in terms of image detection timing, difference is about data image load time.
I had created some logs with timestamp in simple BAT file:
```
@echo %time%
curl -H 'ContentType: multipart/form-data' -i -X POST -F "file=@test1.jpg" http://192.168.99.100:5001/upload
@echo %time%
```
that's my output for a 63K image file:

```
c:\yolo>test.bat
 **0:42:13,60**

c:\yolo>curl -H 'ContentType: multipart/form-data' -i -X POST -F "file=@test1.jpg" http://192.168.99.100:5001/upload
curl: (6) Could not resolve host: multipart
HTTP/1.1 100 Continue

HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 173
Server: Werkzeug/0.16.0 Python/3.7.4
Date: Sat, 18 Jan 2020 23:42:21 GMT

{"id":"/view/15431f3b-3284-4d55-9ecb-b7787edd0eb1","info":{"object_string":"","objects":[],"scored_objects":[],"success":true,"timings":"detect_img: 2.919s, meta: 0.0s, "}}
 **0:42:23,51**
```
So you can see entire process took ~10s, and as JSON reply suggest ,less than 3 sec for model interpretation.

This is the frontend log after I dragged 5 images: with same comparable size

```
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:04] "GET / HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:27] "POST /upload HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:27] "GET /view/04c1fba0-3f6b-406e-8714-316cbbef676e HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:30] "POST /upload HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:31] "GET /view/9e97dd53-d11e-4482-ac4b-9d584d322071 HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:34] "POST /upload HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:34] "GET /view/fc2aa389-1b01-4ad6-9dab-af4a7ca5b1f1 HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:37] "POST /upload HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:37] "GET /view/fa355a96-e551-40c7-a0ec-83f85f578a00 HTTP/1.1" 200 -
processor_1  | INFO:werkzeug:192.168.99.1 - - [18/Jan/2020 23:48:40] "POST /upload HTTP/1.1" 200 
```-

You can see they are way more faster (image load + model interpretation).

So just wonderign why the CURL command needs more time to complete the process.
Thx

**Comment by vulcan25** [comment]
I'm tempted to beleive this is something to do with the `curl` version you're running.  I'm not running on windows, here's the version string from my EC2 Ubuntu box (on the host; not inside a container):
```
$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
```
Also (and I'm not sure if this is the windows version behaving differently):
```
curl: (6) Could not resolve host: multipart
```
`multipart` shouldn't be getting interpreted as a hostname here.  I wonder if the unsuccessful attempt to resolve this hostname is adding the extra time?  

In fact I just checked and you don't need to set the 'ContentType' it appears.  This was probably only required in earlier versions of my script.

So try replacing with:

    curl -i -X POST -F "file=@test1.jpg" http://192.168.99.100:5001/upload

If that still takes too much time, please update this thread with `curl --version`

**Comment by simonfreeman80** [comment]
Hi, that's my CURL version:
```
curl 7.65.3 (x86_64-w64-mingw32) libcurl/7.65.3 OpenSSL/1.1.1c (Schannel) zlib/1.2.11 libidn2/2.2.0 nghttp2/1.39.1
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP
```

**Comment by vulcan25** [comment]
Did omitting the -H flag speed this up much?

**Comment by simonfreeman80** [comment]
@vulcan25  omitting -H flag did solve the speed problem! Thank you! :-)

**Comment by vulcan25** [comment]
Nice one, I'll close this issue for now.  Any more queries do let me know.
